variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip install wheel
  - pip install tox

.base_image: &py3_common
  image: registry.nic.cz/turris/foris-ci/python3

flake8:
  <<: *py3_common
  script:
    - tox -q -e lint

test_python3:
  <<: *py3_common
  script:
    - tox -q -e py39 -- --backend openwrt --backend mock
